export const MedicineInfo = [
  {
    id: 1,
    name: "tab. Inderal 10mg",
    unit: "Tablet",
    packQuantity: 50,
    packPrice: 120,
  },
  {
    id: 2,
    name: "tab. Inderal 10mg",
    unit: "Tablet",
    packQuantity: 50,
    packPrice: 135,
  },
  {
    id: 3,
    name: "tab. Levetra 10mg",
    unit: "Tablet",
    packQuantity: 50,
    packPrice: 135,
  },
  {
    id: 4,
    name: "tab. Stomek 10mg",
    unit: "Tablet",
    packQuantity: 50,
    packPrice: 1135,
  },
  {
    id: 5,
    name: "Inj. Methycobal 10's",
    unit: "Injection",
    packQuantity: 10,
    packPrice: 1150,
  },
  {
    id: 6,
    name: "Inj. Risek 40mg",
    unit: "Injection",
    packQuantity: 1,
    packPrice: 389,
  },
  {
    id: 7,
    name: "Inj. Omega 40mg",
    unit: "Injection",
    packQuantity: 1,
    packPrice: 350,
  },
  {
    id: 8,
    name: "Inj. Levetra",
    unit: "Injection",
    packQuantity: 1,
    packPrice: 289,
  },
  {
    id: 9,
    name: "Tab. Voltral 50mg 20's",
    unit: "Tablet",
    packQuantity: 20,
    packPrice: 266,
  },
  {
    id: 10,
    name: "Cap. Risek 40mg 14's",
    unit: "Capsule",
    packQuantity: 14,
    packPrice: 366,
  },
];
